### ISSUE TITLE
Duplicate fields

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/recipe#5]
Ingredients, Preparation time, and Cooking time are displaying as duplicate fields in the recipe content type.  The "Recipe module element" version of these duplicates works as intended, as far as I've tested.  I think the version of these fields that have configuration options should be removed.

![image](https://user-images.githubusercontent.com/124289165/234084727-24bbd8c1-5884-4584-ab10-773784376583.png)

**Comment by argiepiano** [comment]
Hi @pgrayove-mcpl.

This happened because you most likely installed the failed ported module (or perhaps version 2 of the port) initially, before installing version 1 of Recipe. When you installed that initial version, the module created several field configuration files in `files/config_XXX/active` - those would look like `field.field.recipe_cook_time.json` and `field.instance.recipe.recipe_cook_time.json`. When you uninstalled that initial version of `recipe`, those json files were left over. So, then you installed version 1 of the module, but your site still thinks those fields exist, thus it's listing two fields: one for the internal fields created by version 1, and another one for the Field API fields created by your previously installed version.

So, what is the solution here? Ideally, you would be installing version 1 in a COMPLETELY new Backdrop installation. This means, NO files in your `file/config_XXX` folder. You would install Backdrop from scratch, and then install Recipe.

Alternatively, one quick solution that would not require completely reinstalling your site is to simply delete those extra fields in the UI. For example, in the UI photo you posted, look for Cooking time, and click on the little dropdown button, and do a delete.

Again, to clarify: version 1 will not install those duplicate fields. They are leftovers from a previous installation.

**Comment by pgrayove-mcpl** [comment]
Ah, I wondered if that was the case.  Yeah, I'll just delete those extra fields.

**Comment by argiepiano** [comment]
One more thing: you are likely to get fatal errors when you delete those fields, because the database tables probably don't exist anymore for those.

If you do get fatal errors, then I suggest you manually remove those json files for each duplicate field from your config directory and clear caches. That should be enough to remove those duplications.

**Comment by pgrayove-mcpl** [comment]
That worked and may also have solved #4 with array to string conversion and fields not saving.  I guess I'm creating issues that don't really exist.  Thank you for being patient as I figure things out.
